SELECT COMPANY_CODE
     , FOUNDER
     , (SELECT COUNT(DISTINCT LEAD_MANAGER_CODE) FROM LEAD_MANAGER
        WHERE COMPANY_CODE = A.COMPANY_CODE)
     , (SELECT COUNT(DISTINCT SENIOR_MANAGER_CODE) FROM SENIOR_MANAGER
        WHERE COMPANY_CODE = A.COMPANY_CODE)
     , (SELECT COUNT(DISTINCT MANAGER_CODE) FROM MANAGER
        WHERE COMPANY_CODE = A.COMPANY_CODE)
     , (SELECT COUNT(DISTINCT EMPLOYEE_CODE) FROM EMPLOYEE
        WHERE COMPANY_CODE = A.COMPANY_CODE)
FROM COMPANY A
ORDER BY A.COMPANY_CODE;


/*
|A-C| + |B-D|
*/
SELECT ROUND(ABS(MAX(LAT_N) - MIN(LAT_N)) + ABS(MAX(LONG_W) - MIN(LONG_W)), 4)
FROM STATION;
